from PIL import Image, ImageDraw, ImageFont
from datetime import datetime
from typing import List, Dict
import os

class DayViewGenerator:
    """Generate visual day view image from items"""
    
    def __init__(self, output_dir='backend/static/visualizations'):
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)
        self.width = 900
        self.height = 1200
        self.bg_color = (250, 251, 252)
        
        self.colors = {
            'task': (16, 185, 129),
            'note': (59, 130, 246),
            'reminder': (245, 158, 11),
            'high': (239, 68, 68),
            'medium': (245, 158, 11),
            'low': (59, 130, 246),
            'manual': (100, 116, 139),
            'calendar': (139, 92, 246),
            'email': (236, 72, 153)
        }

    def generate(self, date: str, items: List[Dict]) -> str:
        """Generate visual day view image"""
        
        img = Image.new('RGB', (self.width, self.height), self.bg_color)
        draw = ImageDraw.Draw(img)
        
        # Load fonts
        try:
            title_font = ImageFont.truetype("arial.ttf", 48)
            subtitle_font = ImageFont.truetype("arial.ttf", 28)
            time_font = ImageFont.truetype("arial.ttf", 22)
            text_font = ImageFont.truetype("arial.ttf", 20)
            small_font = ImageFont.truetype("arial.ttf", 16)
        except:
            title_font = ImageFont.load_default()
            subtitle_font = ImageFont.load_default()
            time_font = ImageFont.load_default()
            text_font = ImageFont.load_default()
            small_font = ImageFont.load_default()
    
        # Header
        date_obj = datetime.fromisoformat(date)
        header_text = date_obj.strftime('%A, %B %d, %Y')
        draw.text((50, 40), header_text, fill=(15, 23, 42), font=title_font)
        
        # Stats
        stats_y = 120
        total_tasks = len([i for i in items if i['type'] == 'task'])
        total_reminders = len([i for i in items if i['type'] == 'reminder'])
        total_notes = len([i for i in items if i['type'] == 'note'])
        
        self._draw_stat_box(draw, 50, stats_y, "Tasks", total_tasks, self.colors['task'], text_font)
        self._draw_stat_box(draw, 300, stats_y, "Reminders", total_reminders, self.colors['reminder'], text_font)
        self._draw_stat_box(draw, 550, stats_y, "Notes", total_notes, self.colors['note'], text_font)
        
        # Source legend
        legend_y = stats_y + 90
        draw.text((50, legend_y), "Sources:", fill=(71, 85, 105), font=small_font)
        self._draw_legend(draw, 150, legend_y, "✍️ Manual", self.colors['manual'], small_font)
        self._draw_legend(draw, 300, legend_y, "📅 Calendar", self.colors['calendar'], small_font)
        self._draw_legend(draw, 470, legend_y, "📧 Email", self.colors['email'], small_font)
        
        # Timeline
        timeline_y = legend_y + 90
        draw.text((50, timeline_y), "Timeline", fill=(15, 23, 42), font=subtitle_font)
        
        y_offset = timeline_y + 50
        
        # Sort items by datetime
        sorted_items = sorted(
            [i for i in items if i.get('datetime')],
            key=lambda x: x['datetime']
        )
        
        no_time_items = [i for i in items if not i.get('datetime')]
        
        # If no items, show message
        if not sorted_items and not no_time_items:
            draw.text((50, y_offset), "No items scheduled for this day", fill=(148, 163, 184), font=text_font)
            y_offset += 60
            draw.text((50, y_offset), "Add tasks, notes, or reminders to see them here!", fill=(203, 213, 225), font=small_font)
        else:
            # Render timed items
            for item in sorted_items[:10]:  # Show more items
                if y_offset < self.height - 200:  # Leave space for footer
                    y_offset = self._draw_timeline_item(draw, item, y_offset, time_font, text_font, small_font)
            
            # Render no-time items
            if no_time_items and y_offset < self.height - 200:
                draw.text((50, y_offset), "No Specific Time", fill=(100, 116, 139), font=text_font)
                y_offset += 40
                
                for item in no_time_items[:5]:  # Show more items
                    if y_offset < self.height - 200:
                        y_offset = self._draw_simple_item(draw, item, y_offset, text_font, small_font)
        
        # Footer
        footer_y = self.height - 60
        footer_text = f"Generated by Productivity Assistant • {datetime.now().strftime('%I:%M %p')}"
        draw.text((50, footer_y), footer_text, fill=(148, 163, 184), font=small_font)
        
        # Save
        filename = f"day_view_{date}.png"
        filepath = os.path.join(self.output_dir, filename)
        img.save(filepath, quality=95)
    
        return f"/static/visualizations/{filename}"

    def _draw_stat_box(self, draw, x, y, label, count, color, font):
        """Draw stat box"""
        draw.rectangle([(x, y), (x + 200, y + 70)], fill=(255, 255, 255), outline=color, width=3)
        draw.text((x + 20, y + 15), label, fill=(71, 85, 105), font=font)
        draw.text((x + 20, y + 40), str(count), fill=color, font=font)

    def _draw_legend(self, draw, x, y, text, color, font):
        """Draw legend item"""
        draw.ellipse([(x, y + 2), (x + 12, y + 14)], fill=color)
        draw.text((x + 20, y), text, fill=(71, 85, 105), font=font)

    def _draw_timeline_item(self, draw, item, y, time_font, text_font, small_font):
        """Draw timeline item card"""
        card_height = 110
        
        priority_color = self.colors.get(item.get('priority', 'medium'), self.colors['medium'])
        source_color = self.colors.get(item.get('source', 'manual'), self.colors['manual'])
        
        # Card background
        draw.rectangle(
            [(50, y), (850, y + card_height)],
            fill=(255, 255, 255),
            outline=priority_color,
            width=4
        )
        
        # Left border (source indicator)
        draw.rectangle(
            [(50, y), (58, y + card_height)],
            fill=source_color
        )
        
        # Time
        dt = datetime.fromisoformat(item['datetime'])
        time_str = dt.strftime('%I:%M %p')
        draw.text((75, y + 15), time_str, fill=priority_color, font=time_font)
        
        # Title
        title = item['title'][:50]
        draw.text((230, y + 15), title, fill=(15, 23, 42), font=text_font)
        
        # Badges
        type_badge = f"[{item['type'].upper()}]"
        priority_badge = f"{item.get('priority', 'medium').upper()}"
        
        draw.text((75, y + 50), type_badge, fill=self.colors[item['type']], font=small_font)
        draw.text((75, y + 75), priority_badge, fill=priority_color, font=small_font)
        
        # Source
        source_emoji = {'manual': '✍️', 'calendar': '📅', 'email': '📧'}.get(item.get('source'), '📌')
        draw.text((230, y + 75), f"{source_emoji} {item.get('source', 'manual').title()}", fill=source_color, font=small_font)
    
        return y + card_height + 15

    def _draw_simple_item(self, draw, item, y, text_font, small_font):
        """Draw simple item without time"""
        draw.ellipse([(50, y + 5), (62, y + 17)], fill=self.colors[item['type']])
        draw.text((75, y), item['title'][:60], fill=(15, 23, 42), font=text_font)
    
        source_emoji = {'manual': '✍️', 'calendar': '📅', 'email': '📧'}.get(item.get('source'), '📌')
        draw.text((75, y + 25), f"{source_emoji} {item.get('source', 'manual')}", fill=(100, 116, 139), font=small_font)
        
        return y + 55